Classroom/Classroom/Models/Test.cs
using System.Collections.Generic;

namespace Classroom.Models
{
    public class Test : UserTask
    {
        public int Id { get; set; }
        public virtual ICollection<TestFileDetail> FileDetails { get; set; }
        public virtual ICollection<VirtualClassroom> Classrooms { get; set; }
        public virtual ICollection<CompletedTest> CompletedTests { get; set; }
        public virtual ICollection<CompletedTestFileDetails> CompletedTestFileDetails { get; set; }

    }
}

Classroom/Classroom/ViewModels/TestViewModel.cs
using Classroom.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Classroom.ViewModels
{
    public class TestViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Available { get; set; }

        [Display(Name = "Available Date")]
        public DateTime? AvailableDate { get; set; }

        [Display(Name = "Due Date")]
        public DateTime? DueDate { get; set; }

        [Display(Name = "Points Worth")]
        public int PointsWorth { get; set; }

        public ICollection<Test> Tests { get; set; }

        [Display(Name = "Completed Tests")]
        public ICollection<CompletedTest> CompletedTests { get; set; }

        [Display(Name = "Classrooms")]
        public int ClassroomId { get; set; }

        public IEnumerable<VirtualClassroom> VirtualClassrooms { get; set; }
    }
}

Classroom/Classroom/Controllers/TestsController.cs
using Classroom.Models;
using Classroom.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Classroom.Controllers
{
    [Authorize(Roles = "Instructor")]
    public class TestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public TestsController()
        {
            _context = new ApplicationDbContext();
        }

        public TestsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        // GET: Tests
        public async Task<ActionResult> Index()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var classrooms = user.Instructor.VirtualClassrooms;
            var viewModel = new VirtualClassroomViewModel()
            {
                Tests = new List<Test>(),
                CompletedTests = new List<CompletedTest>(),
                VirtualClassrooms = classrooms
            };
            foreach (var classroom in classrooms)
            {
                foreach (var test in classroom.Tests)
                {
                    viewModel.Tests.Add(test);
                    foreach (var completedTest in test.CompletedTests.Where(s => s.Submitted))
                    {
                        viewModel.CompletedTests.Add(completedTest);
                    }
                }
            }
            return View(viewModel);
        }

        public async Task<ActionResult> ClassroomTests(int? id)
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var classrooms = user.Instructor.VirtualClassrooms;
            var classroom = _context.VirtualClassrooms.Find(id);
            var viewModel = new VirtualClassroomViewModel()
            {
                VirtualClassroom = classroom,
                VirtualClassrooms = classrooms,
                Tests = classroom.Tests.ToList(),
                CompletedTests = _context.CompletedTests
                .Where(x => x.VirtualClassroom.Id == id
                && x.Submitted
                && x.Graded == false).ToList(),
            };
            return View(viewModel);
        }

        // GET: Tests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = _context.Tests.Find(id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        //// GET: Tests/Create
        //public async Task<ActionResult> Create()
        //{
        //    var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
        //    var viewModel = new TestsFormViewModel
        //    {
        //        VirtualClassrooms = user.Instructor.VirtualClassrooms,
        //        AvailableDate = null,
        //        DueDate = null,
        //    };
        //    return View(viewModel);
        //}

        public ActionResult _Create()
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var viewModel = new VirtualClassroomViewModel()
            {
                VirtualClassrooms = user.Instructor.VirtualClassrooms
            };
            return PartialView(viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VirtualClassroomViewModel viewModel, string[] selectedClassrooms)
        {
            var test = new Test
            {
                TaskTitle = viewModel.Test.TaskTitle,
                TaskDescription = viewModel.Test.TaskDescription,
                TaskAvailable = viewModel.Test.TaskAvailable,
                AvailableDate = (DateTime)viewModel.Test.AvailableDate,
                DueDate = (DateTime)viewModel.Test.DueDate,
                PointsWorth = viewModel.Test.PointsWorth,
                Classrooms = new List<VirtualClassroom>()
            };
            foreach (var classroomId in selectedClassrooms)
            {
                var classroom = _context.VirtualClassrooms.Find(int.Parse(classroomId));
                test.Classrooms.Add(classroom);
            }
            foreach (var classroom in test.Classrooms)
            {
                foreach (var student in classroom.Students)
                {
                    Grade grade = new Grade()
                    {
                        Id = Guid.NewGuid(),
                        PointsReceived = 0
                    };
                    _context.Grades.Add(grade);

                    var completedTest = new CompletedTest
                    {
                        TestId = test.Id,
                        StudentId = student.StudentId,
                        CompletedDateTime = null,
                        VirtualClassroomId = classroom.Id,
                        GradeId = grade.Id
                    };
                    _context.CompletedTests.Add(completedTest);
                }
            }
            test.FileDetails = AddFilesDetailsToTest();
            _context.Tests.Add(test);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        private List<TestFileDetail> AddFilesDetailsToTest()
        {
            List<TestFileDetail> fileDetails = new List<TestFileDetail>();
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    TestFileDetail fileDetail = new TestFileDetail()
                    {
                        FileName = fileName,
                        Extension = Path.GetExtension(fileName),
                        FileId = Guid.NewGuid()
                    };
                    fileDetails.Add(fileDetail);

                    var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"),
                        fileDetail.FileId + fileDetail.Extension);
                    file.SaveAs(path);
                }
            }
            return fileDetails;
        }

        public FileResult Download(string p, string d)
        {
            return File(Path.Combine(Server.MapPath("~/App_Data/Upload/"), p),
                System.Net.Mime.MediaTypeNames.Application.Octet, d);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Test test = _context.Tests
                .Include(f => f.FileDetails)
                .SingleOrDefault(a => a.Id == id);
            if (test == null)
            {
                return HttpNotFound();
            }
            return View(test);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "Id,TaskTitle,TaskDescription,TaskAvailable,AvailableDate,DueDate,PointsWorth")] Test
                test)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        TestFileDetail fileDetail = new TestFileDetail()
                        {
                            FileName = fileName,
                            Extension = Path.GetExtension(fileName),
                            FileId = Guid.NewGuid(),
                            TestId = test.Id
                        };
                        var path = Path.Combine(Server.MapPath("~/App_Data/Upload/"),
                            fileDetail.FileId + fileDetail.Extension);
                        file.SaveAs(path);

                        _context.Entry(fileDetail).State = EntityState.Added;
                    }
                }
                _context.Entry(test).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(test);
        }

        [HttpPost]
        public JsonResult DeleteFile(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Result = "Error" });
            }
            try
            {
                Guid guid = new Guid(id);
                TestFileDetail fileDetail = _context.TestFileDetails.Find(guid);
                if (fileDetail == null)
                {
                    Response.StatusCode = (int)HttpStatusCode.NotFound;
                    return Json(new { Result = "Error" });
                }

Classroom/Classroom/Views/Tests/Create.cshtml
@model Classroom.ViewModels.TestViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Instructor.cshtml";
}



<div class="classroom-form">
    <h2>New Test</h2>
    @using (Html.BeginForm("Create", "Tests", null, FormMethod.Post, new {enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <p class="alert alert-info">All fields are <strong>required</strong>.
        </p>


        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Title)

            @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control", autofocus = "autofocus"}})
            @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description)

            @Html.TextAreaFor(model => model.Description, new {@class = "form-control"})
            @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableDate)

            @Html.EditorFor(model => model.AvailableDate, new {htmlAttributes = new {@class = "form-control", id = "availabledatepicker"}})
            @Html.ValidationMessageFor(model => model.AvailableDate, "", new {@class = "text-danger"})

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate)

            @Html.EditorFor(model => model.DueDate, new {htmlAttributes = new {@class = "form-control", id = "duedatepicker"}})
            @Html.ValidationMessageFor(model => model.DueDate, "", new {@class = "text-danger"})

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PointsWorth)

            @Html.EditorFor(model => model.PointsWorth, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.PointsWorth, "", new {@class = "text-danger"})

        </div>
        <div class="form-group">
            @Html.Label("Files:")
        </div>
        <div class="input-group">
            <label class="input-group-btn">
                <span class="btn btn-primary">
                Browse&hellip; <input type="file" name="file" style="display: none;" multiple>
            </span>
            </label>
            <input type="text" class="form-control" placeholder="No Files Selected" readonly>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.VirtualClassrooms)
            <div class="form-group checkboxlist">
                @foreach (var classroom in Model.VirtualClassrooms)
                {
                    <input type="checkbox" name="selectedClassrooms" value="@classroom.Id"/>
                    @classroom.ClassroomName<br/>
                }
            </div>
            @Html.ValidationMessageFor(model => model.ClassroomId, "", new {@class = "text-danger"})
        </div>

        <div class="form-group">

            <input type="submit" value="Create" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>

    }
</div>

@section Scripts{
    <script>
        $(function () {

            // We can attach the `fileselect` event to all file inputs on the page
            $(document).on('change', ':file', function () {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });

            // We can watch for our custom `fileselect` event like this
            $(document).ready(function () {
                $(':file').on('fileselect', function (event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label;

                    if (input.length) {
                        input.val(log);
                    } else {
                        if (log) alert(log);
                    }

                });
            });

        });

        $(function () {
            $("#duedatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
        $(function () {
            $("#availabledatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });

    </script>
}

Classroom/Classroom/Views/Tests/Delete.cshtml
@model Classroom.Models.Test

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Instructor.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment: @Model.TaskTitle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PointsWorth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PointsWorth)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Classroom/Classroom/Views/Tests/Details.cshtml
@model Classroom.Models.Test

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Instructor.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Assignment: @Model.TaskTitle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TaskTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaskAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaskAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PointsWorth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PointsWorth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Classrooms)
        </dt>
        <dd>
            @foreach (var classroom in Model.Classrooms)
            {
                @Html.Display(classroom.ClassroomName)
            }
        </dd>
        <dt>
            @Html.Label("Files:")
        </dt>
        <dd>

            @foreach (var item in Model.FileDetails)
            {

                <a class="btn btn-success btn-sm" href="/Assignments/Download/?p=@(item.FileId + item.Extension)&d=@item.FileName">@item.FileName</a>
                        <p></p>
            }

        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Classroom/Classroom/Views/Tests/Edit.cshtml
@model Classroom.Models.Test

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Instructor.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Tests", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Assignment: @Model.TaskTitle</h4>
        <p class="alert alert-info">All fields are <strong>required</strong>.</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TaskTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskTitle, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.TaskTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TaskDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TaskDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.TaskAvailable)
                    @Html.ValidationMessageFor(model => model.TaskAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AvailableDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PointsWorth, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.PointsWorth, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.PointsWorth, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Files:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="input-group">
                    <label class="input-group-btn">
                        <span class="btn btn-primary">
                            Browse&hellip; <input type="file" name="file" style="display: none;" multiple>
                        </span>
                    </label>
                    <input type="text" class="form-control" placeholder="No Files Selected" readonly>
                </div>
                <br />
                <ul class="attachment">
                    @foreach (var item in Model.FileDetails)
                {
                        <li>
                            <a class="btn btn-success" href="/Assignments/Download/?p=@(item.FileId + item.Extension)&d=@item.FileName">@item.FileName</a>
                            <a href="javascript:void(0);" data-id="@item.FileId" class="deleteItem"><i class="fa fa-times" style="color: red" aria-hidden="true"></i></a>
                            <p></p>
                        </li>
                    }
                </ul>
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section scripts{
 <script>
    $('.deleteItem').click(function (e) {
           e.preventDefault();
           var $ctrl = $(this);
           if (confirm('Do you really want to delete this file?')) {
               $.ajax({
                   url: '@Url.Action("DeleteFile")',
                   type: 'POST',
                   data: { id: $(this).data('id') }
               }).done(function(data) {
                   if (data.Result == "OK") {
                       $ctrl.closest('li').remove();
                   } else if (data.Result.Message) {
                       alert(data.Result.Message);
                   }
               }).fail(function() {
                   alert("There is something wrong. Please try again.");
               });

           }
    });

     $(function () {

         // We can attach the `fileselect` event to all file inputs on the page
         $(document).on('change', ':file', function () {
             var input = $(this),
                 numFiles = input.get(0).files ? input.get(0).files.length : 1,
                 label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
             input.trigger('fileselect', [numFiles, label]);
         });

         // We can watch for our custom `fileselect` event like this
         $(document).ready(function () {
             $(':file').on('fileselect', function (event, numFiles, label) {

                 var input = $(this).parents('.input-group').find(':text'),
                     log = numFiles > 1 ? numFiles + ' files selected' : label;

                 if (input.length) {
                     input.val(log);
                 } else {
                     if (log) alert(log);
                 }

             });
         });

     });
</script>   
}

Classroom/Classroom/Views/Tests/_Create.cshtml
@model Classroom.ViewModels.VirtualClassroomViewModel

    @using (Html.BeginForm("Create", "Tests", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Test.TaskTitle)

                @Html.EditorFor(model => model.Test.TaskTitle, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                @Html.ValidationMessageFor(model => model.Test.TaskTitle, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Test.TaskDescription)

                @Html.TextAreaFor(model => model.Test.TaskDescription, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Test.TaskDescription, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Test.AvailableDate)

                @Html.EditorFor(model => model.Test.AvailableDate, new { htmlAttributes = new { @class = "form-control", id = "availabledatepicker" } })
                @Html.ValidationMessageFor(model => model.Test.AvailableDate, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Test.DueDate)

                @Html.EditorFor(model => model.Test.DueDate, new { htmlAttributes = new { @class = "form-control", id = "duedatepicker" } })
                @Html.ValidationMessageFor(model => model.Test.DueDate, "", new { @class = "text-danger" })

            </div>

        </div>

        <div class="col-md-6">

            <div class="form-group">
                @Html.LabelFor(model => model.Test.PointsWorth)

                @Html.EditorFor(model => model.Test.PointsWorth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Test.PointsWorth, "", new { @class = "text-danger" })

            </div>
            <div class="form-group">
                @Html.Label("Files:")
            </div>
            <div class="input-group">
                <label class="input-group-btn">
                    <span class="btn btn-primary">
                        Browse&hellip; <input type="file" name="file" style="display: none;" multiple>
                    </span>
                </label>
                <input type="text" class="form-control" placeholder="No Files Selected" readonly>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.VirtualClassrooms)
                <div class="form-group checkboxlist">
                    @foreach (var classroom in Model.VirtualClassrooms)
                {
                        <input type="checkbox" name="selectedClassrooms" value="@classroom.Id" />
                        @classroom.ClassroomName<br />
                    }
                </div>
                @Html.ValidationMessageFor(model => model.ClassroomId, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">

                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
        

    }

@section Scripts{
    <script>
        $(function () {

            // We can attach the `fileselect` event to all file inputs on the page
            $(document).on('change', ':file', function () {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });

            // We can watch for our custom `fileselect` event like this
            $(document).ready(function () {
                $(':file').on('fileselect', function (event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label;

                    if (input.length) {
                        input.val(log);
                    } else {
                        if (log) alert(log);
                    }

                });
            });

        });

        $(function () {
            $("#duedatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
        $(function () {
            $("#availabledatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });

    </script>
}