Classroom/Classroom/Models/Semester.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Classroom.Models
{
    public class Semester
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public bool Active { get; set; }

        [Required]
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Required]
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

    }
}

Classroom/Classroom/Controllers/SemestersController.cs
using Classroom.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Classroom.Controllers
{
    public class SemestersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SemestersController()
        {
            _context = new ApplicationDbContext();;
        }

        public ActionResult Index()
        {
            return View(_context.Semesters.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Semester semester = _context.Semesters.Find(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult _Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Active,StartDate,EndDate")] Semester semester)
        {
            if (ModelState.IsValid)
            {
                _context.Semesters.Add(semester);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(semester);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Semester semester = _context.Semesters.Find(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Active,StartDate,EndDate")] Semester semester)
        {
            if (ModelState.IsValid)
            {
                _context.Entry(semester).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(semester);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Semester semester = _context.Semesters.Find(id);
            if (semester == null)
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Semester semester = _context.Semesters.Find(id);
            _context.Semesters.Remove(semester);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Classroom/Classroom/Views/Semesters/Create.cshtml
@model Classroom.Models.Semester

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="classroom-form">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <h2>New Semester</h2>
        <p class="alert alert-info">
            All fields are <strong>required</strong>.
        </p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate)
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", id = "startdatepicker" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate)
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", id = "enddatepicker" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-default" />

        </div>

    }
    @Html.ActionLink("Back to List", "Index")
</div>



@section Scripts{
    <script>
        $(function () {
            $("#startdatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
        $(function () {
            $("#enddatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
    </script>
}

Classroom/Classroom/Views/Semesters/Delete.cshtml
@model Classroom.Models.Semester

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Semester: @Model.Title</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Classroom/Classroom/Views/Semesters/Details.cshtml
@model Classroom.Models.Semester

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Semester: @Model.Title</h4>
    <hr/>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Classroom/Classroom/Views/Semesters/Edit.cshtml
@model Classroom.Models.Semester

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="classroom-form">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <h4>Semester: @Model.Title</h4>
        <p class="alert alert-info">All fields are <strong>required</strong>.</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title)

            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate)

            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate)

            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">

            <input type="submit" value="Save" class="btn btn-default" />


        </div>

    }
    @Html.ActionLink("Back to List", "Index")
</div>

Classroom/Classroom/Views/Semesters/Index.cshtml
@model IEnumerable<Classroom.Models.Semester>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="panel panel-danger">
    <div class="panel-heading">
        <label>New Semester</label>
    </div>
    <div class="panel-body">
        @Html.Action("_Create", "Semesters")
    </div>
</div>

<div class="panel panel-danger">
    <div class="panel-heading">
        <label>Semesters</label>
    </div>
    <div class="panel-body">
        <table class="table table-stripped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-pencil-square-o btn btn-primary btn-sm", title = "Edit" })
                        @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "fa fa-list btn btn-success btn-sm", title = "Details" })
                        @Html.ActionLink(" ", "Delete", new {id = item.Id }, new { @class ="fa fa-trash-o btn btn-danger btn-sm", title = "Delete"})
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Classroom/Classroom/Views/Semesters/_Create.cshtml
@model Classroom.Models.Semester

    @using (Html.BeginForm("Create", "Semesters"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.Title)
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control", autofocus = "autofocus"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate)
                @Html.EditorFor(model => model.StartDate, new {htmlAttributes = new {@class = "form-control", id = "startdatepicker"}})
                @Html.ValidationMessageFor(model => model.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.EndDate)
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", id = "enddatepicker" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>

            </div>
        </div>

    }




@section Scripts{
    <script>
        $(function () {
            $("#startdatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
        $(function () {
            $("#enddatepicker").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true
            });
        });
    </script>
}