Classroom/Classroom/Models/Assignment.cs
using System.Collections.Generic;

namespace Classroom.Models
{
    public class Assignment : UserTask
    {
        public int Id { get; set; }
        public virtual ICollection<AssignmentFileDetail> FileDetails { get; set; }
        public virtual  ICollection<VirtualClassroom> Classrooms { get; set; }
        public virtual ICollection<CompletedAssignment> CompletedAssignments { get; set; }
        public virtual ICollection<CompletedAssignmentFileDetails> CompletedAssignmentFileDetails { get; set; }
    }
}

Classroom/Classroom/Models/CompletedAssignment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Classroom.Models
{
    public class CompletedAssignment
    {
        [Key]
        [Column(Order = 1)]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Submitted { get; set; } = false;
        [ForeignKey("Assignment")]
        [Column(Order = 2)]
        public int AssignmentId { get; set; }
        public virtual Assignment Assignment { get; set; }
        [ForeignKey("VirtualClassroom")]
        [Column(Order = 3)]
        public int VirtualClassroomId { get; set; }
        public virtual VirtualClassroom VirtualClassroom { get; set; }
        public int StudentId { get; set; }
        public Student Student { get; set; }
        public Guid GradeId { get; set; }
        public Grade Grade { get; set; }
        public bool Graded { get; set; } = false;
        [Display(Name = "Date & Time Completed")]
        public DateTime? CompletedDateTime { get; set; }
        public virtual ICollection<CompletedAssignmentFileDetails>  CompletedAssignmentFileDetails { get; set; }

    }
}

Classroom/Classroom/Models/Test.cs
using System.Collections.Generic;

namespace Classroom.Models
{
    public class Test : UserTask
    {
        public int Id { get; set; }
        public virtual ICollection<TestFileDetail> FileDetails { get; set; }
        public virtual ICollection<VirtualClassroom> Classrooms { get; set; }
        public virtual ICollection<CompletedTest> CompletedTests { get; set; }
        public virtual ICollection<CompletedTestFileDetails> CompletedTestFileDetails { get; set; }

    }
}

Classroom/Classroom/ViewModels/EditAssignmentViewModel.cs
using Classroom.Models;

namespace Classroom.ViewModels
{
    public class EditAssignmentViewModel
    {
        public CompletedAssignment CompletedAssignment { get; set; }
        public Assignment Assignment { get; set; }

        public VirtualClassroom VirtualClassroom { get; set; }
    }
}

Classroom/Classroom/Controllers/CompletedTestsController.cs
using Classroom.Models;
using Classroom.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Classroom.Controllers
{
    public class CompletedTestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public CompletedTestsController()
        {
            _context = new ApplicationDbContext();
        }

        public CompletedTestsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get { return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>(); }
            private set { _signInManager = value; }
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }
        // GET: CompletedTests
        public async Task<ActionResult> Index(int? id, int? classroomId)
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var viewModel = new VirtualClassroomViewModel()
            {
                Test = _context.Tests.Find(id),
                VirtualClassroom = _context.VirtualClassrooms.Find(classroomId),
                VirtualClassrooms = user.Instructor.VirtualClassrooms,
                CompletedTests = _context.CompletedTests
                .Include(s => s.Student)
                .Where(s => s.Submitted
                && s.TestId == id
                && s.Graded == false).ToList()
            };
            return View(viewModel);
        }

        public async Task<ActionResult> Edit(int? id, int? classroomId)
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var viewModel = new VirtualClassroomViewModel()
            {
                VirtualClassroom = _context.VirtualClassrooms.Find(classroomId),
                VirtualClassrooms = user.Instructor.VirtualClassrooms,
                CompletedTest = _context.CompletedTests.Find(id)
            };
            if (viewModel == null)
            {
                return HttpNotFound();
            }
            //ViewBag.TestId = new SelectList(db.Tests, "TestId", "TaskTitle", completedTest.CompletedTest.TestId);
            //ViewBag.StudentId = new SelectList(db.Students, "StudentId", "FirstName", completedTest.CompletedTest.StudentId);
            return View(viewModel);
        }

        // POST: CompletedTests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VirtualClassroomViewModel viewModel)
        {
            var test = _context.Tests.Find(viewModel.CompletedTest.TestId);
            var editedTest = _context.CompletedTests.Find(viewModel.CompletedTest.Id);
            editedTest.Grade = _context.Grades.Find(viewModel.CompletedTest.GradeId);
            editedTest.Grade.PointsReceived = viewModel.CompletedTest.Grade.PointsReceived;
            editedTest.Grade.GradePercentage = Grade.GetGradePercentage(test.PointsWorth, viewModel.CompletedTest.Grade.PointsReceived);
            editedTest.Graded = true;
            if (ModelState.IsValid)
            {
                _context.CompletedTests.AddOrUpdate(editedTest);
                //db.Entry(editedTest).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index", new { id = viewModel.CompletedTest.TestId, classroomId = viewModel.CompletedTest.VirtualClassroomId });
            }
            ViewBag.TestId = new SelectList(_context.Tests, "Id", "TaskTitle", viewModel.CompletedTest.TestId);
            ViewBag.StudentId = new SelectList(_context.Students, "StudentId", "FirstName", viewModel.StudentId);
            return View(viewModel);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }

                if (_signInManager != null)
                {
                    _signInManager.Dispose();
                    _signInManager = null;
                }
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Classroom/Classroom/Controllers/VirtualClassroomsController.cs
using Classroom.Models;
using Classroom.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Classroom.Controllers
{
    [Authorize]
    public class VirtualClassroomsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public VirtualClassroomsController()
        {
            _context = new ApplicationDbContext();
        }

        public VirtualClassroomsController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;

        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        [Authorize(Roles = "Student")]
        public async Task<ActionResult> StudentClassroom(VirtualClassroomViewModel viewModel)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var classroom = new VirtualClassroomViewModel
            {
                VirtualClassrooms = user.Student.VirtualClassrooms,
                VirtualClassroom = _context.VirtualClassrooms.Find(viewModel.VirtualClassroom.Id)
            };
            return View(classroom);
        }

        [Authorize(Roles = "Instructor")]
        public async Task<ActionResult> InstructorClassroom(VirtualClassroomViewModel viewModel)
        {
            ApplicationUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            var classroom = new VirtualClassroomViewModel
            {
                VirtualClassrooms = user.Instructor.VirtualClassrooms,
                VirtualClassroom = _context.VirtualClassrooms.Find(viewModel.VirtualClassroom.Id)
            };
            return View(classroom);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AdminIndex()
        {
            var classrooms = _context.VirtualClassrooms
                .Include(s => s.Semester)
                .Include(a => a.Administrator)
                .Include(c => c.Course)
                .Include(i => i.Instructors)
                .Include(s => s.Students);
            return View(classrooms);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var viewModel = new VirtualClassroomFormViewModel
            {
                Courses = _context.Courses.ToList(),
                Semesters = _context.Semesters.ToList(),
                Instructors = _context.Instructors.ToList(),
                Students = _context.Students.ToList()
            };
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult _Create()
        {
            var viewModel = new VirtualClassroomFormViewModel
            {
                Courses = _context.Courses.ToList(),
                Semesters = _context.Semesters.ToList(),
                Instructors = _context.Instructors.ToList(),
                Students = _context.Students.ToList()
            };
            return PartialView(viewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VirtualClassroomFormViewModel viewModel, string[] selectedInstructors, string[] selectedStudents)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Courses = _context.Courses.ToList();
                return View("_Create", viewModel);
            }
            var virtualClassroom = new VirtualClassroom
            {
                AdministratorId = User.Identity.GetUserId(),
                ClassroomName = viewModel.ClassroomName,
                SemesterId = viewModel.SemesterId,
                CourseId = viewModel.CourseId,
                Instructors = new List<Instructor>(),
                Students = new List<Student>()
            };
            foreach (var instructorId in selectedInstructors)
            {
                var instructors = _context.Instructors.Find(int.Parse(instructorId));
                virtualClassroom.Instructors.Add(instructors);
            }
            foreach (var studentId in selectedStudents)
            {
                var students = _context.Students.Find(int.Parse(studentId));
                virtualClassroom.Students.Add(students);
            }


            _context.VirtualClassrooms.Add(virtualClassroom);
            _context.SaveChanges();

            return RedirectToAction("AdminIndex");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var classroom = _context.VirtualClassrooms.Find(id);
            if (classroom == null)
            {
                return HttpNotFound();
            }
            return View(classroom);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VirtualClassroom virtualInstructor =
                _context.VirtualClassrooms
                    .Include(s => s.Instructors)
                    .Single(v => v.Id == id);
            VirtualClassroom virtualStudent =
                _context.VirtualClassrooms
                    .Include(s => s.Students)
                    .Single(v => v.Id == id);
            PopulateAssignedInstructorData(virtualInstructor);
            PopulateAssignedStudentData(virtualStudent);
            VirtualClassroom virtualClassroom = _context.VirtualClassrooms.Find(id);
            if (virtualClassroom == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseId = new SelectList(_context.Courses, "Id", "Name", virtualClassroom.CourseId);
            ViewBag.SemesterId = new SelectList(_context.Semesters, "Id", "Title", virtualClassroom.SemesterId);
            return View(virtualClassroom);
        }

        // POST: VirtualClassrooms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedInstructors, string[] selectedStudents)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VirtualClassroom virtualInstructor =
                _context.VirtualClassrooms
                    .Include(s => s.Instructors)
                    .Single(v => v.Id == id);
            VirtualClassroom virtualStudent =
                _context.VirtualClassrooms
                    .Include(s => s.Students)
                    .Single(v => v.Id == id);
            if (TryUpdateModel(virtualInstructor, "",
                new string[] { "Id", "ClassroomName", "CourseId", "SemesterId" }))
            {
                try
                {
                    UpdateClassroomInstructors(selectedInstructors, virtualInstructor);
                    UpdateClassroomStudents(selectedStudents, virtualStudent);
                    _context.SaveChanges();
                    return RedirectToAction("AdminIndex");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            else if (TryUpdateModel(virtualStudent, "",
                new string[] { "Id", "ClassroomName", "CourseId", "SemesterId" }))
            {
                try
                {
                    UpdateClassroomStudents(selectedStudents, virtualStudent);
                    UpdateClassroomInstructors(selectedInstructors, virtualInstructor);
                    _context.SaveChanges();
                    return RedirectToAction("AdminIndex");
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedInstructorData(virtualInstructor);
            PopulateAssignedStudentData(virtualStudent);
            VirtualClassroom virtualClassroom = _context.VirtualClassrooms.Find(id);
            if (ModelState.IsValid)
            {
                _context.Entry(virtualClassroom).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("AdminIndex");
            }

Classroom/Classroom/Views/VirtualClassrooms/AdminIndex.cshtml
@model IEnumerable<Classroom.Models.VirtualClassroom>

@{
    ViewBag.Title = "Classrooms";
    Layout = "~/Views/Shared/_Admin.cshtml";

}

<div class="panel panel-danger">
    <div class="panel-heading">
        New Classroom
    </div>
    <div class="panel-body">
        @Html.Action("_Create", "VirtualClassrooms")
    </div>
</div>

<div class="panel panel-danger">
    <div class="panel-heading">
        Classrooms
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ClassroomName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Semester)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Course)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Instructors)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Students)
                </th>


                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClassroomName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Semester.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Course.Name)
                    </td>
                    <td>
                        @if (item.Instructors.Count() == 0)
                        {
                            <span>No Instructors</span>
                        }
                        else
                        {
                            <span>@item.Instructors.Count() Instructor(s)</span>
                        }
                    </td>
                    <td>
                        @if (item.Students.Count() == 0)
                {
                            <span>No Students</span>
                        }
                        else
                        {
                            <span>@item.Students.Count() Student(s)</span>
                        }
                    </td>


                    <td>
                        @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-pencil-square-o btn btn-primary btn-sm", title = "Edit" })
                        @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "fa fa-list btn btn-success btn-sm", title = "Details" })
                        @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash-o btn btn-danger btn-sm", title = "Delete" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Classroom/Classroom/Views/VirtualClassrooms/ClassroomTasks.cshtml
@model Classroom.ViewModels.VirtualClassroomViewModel

@{
    Layout = "~/Views/Shared/_StudentClassroom.cshtml";
}

@Html.Action("_Assignments", "VirtualClassrooms", new { @id = Model.VirtualClassroom.Id })
@Html.Action("_Tests", "VirtualClassrooms", new { @id = Model.VirtualClassroom.Id })




@section Scripts{
    <script>


        $(function () {

            // We can attach the `fileselect` event to all file inputs on the page
            $(document).on('change', ':file', function () {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
            });

            // We can watch for our custom `fileselect` event like this
            $(document).ready(function () {
                $(':file').on('fileselect', function (event, numFiles, label) {

                    var input = $(this).parents('.input-group').find(':text'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label;

                    if (input.length) {
                        input.val(log);
                    } else {
                        if (log) alert(log);
                    }

                });
            });

        });

        $(function () {
            $("#assignmentAccordion").accordion({
                collapsible: true,
                active: 'none',
                heightStyle: "content"
            });
        });
        $(function () {
            $("#testAccordion").accordion({
                collapsible: true,
                active: 'none',
                heightStyle: "content"
            });
        });


    </script>
    <script>
        $(function () {
            $("#editAssignment").on("click", function () {
                $("#editAssignmentDiv").removeClass("hidden");
            });
        });
    </script>

    <script>
        $(function () {
            $("#cancelAssignment").on("click", function () {
                $("#editAssignmentDiv").addClass("hidden");
            });
        });
    </script>
}

Classroom/Classroom/Views/VirtualClassrooms/CompletedAssignment.cshtml
@model Classroom.Models.Assignment

@{
    ViewBag.Title = "CompletedAssignment";
}

<h2>CompletedAssignment</h2>

@using (Html.BeginForm("CompletedAssignment", "VirtualClassrooms", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompletedAssignment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AssignmentId)

        <div class="form-group">
            @Html.Label("Files:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" multiple="multiple" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Classroom/Classroom/Views/VirtualClassrooms/Create.cshtml
@model Classroom.ViewModels.VirtualClassroomFormViewModel
@{
    ViewBag.Title = "Create";
}


<div class="classroom-form">
<h2>New Classroom</h2>

@using (Html.BeginForm("Create", "VirtualClassrooms"))
{
    @Html.AntiForgeryToken()
    <p class="alert alert-info">All fields are <strong>required</strong>.</p>
    <hr/>

    <div class="form-group">
        @Html.LabelFor(m => m.ClassroomName)
        @Html.TextBoxFor(m => m.ClassroomName, new {@class = "form-control", autofocus = "autofocus"})
        @Html.ValidationMessageFor(m => m.ClassroomName, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SemesterId)
        @Html.DropDownListFor(m => m.SemesterId, new SelectList(Model.Semesters, "Id", "Title"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SemesterId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.CourseId)
        @Html.DropDownListFor(m => m.CourseId, new SelectList(Model.Courses, "Id", "Name"), "", new {@class = "form-control"})
        @Html.ValidationMessageFor(m => m.CourseId, "", new {@class = "text-danger"})
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Instructors)
        <div class="form-group checkboxlist">
            @foreach (var instructor in Model.Instructors)
            {
                <input type="checkbox" name="selectedInstructors" value="@instructor.InstructorId"/>
                @instructor.FullName<br/>
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Students)
        <div class="form-group checkboxlist">
            @foreach (var student in Model.Students)
            {
                <input type="checkbox" name="selectedStudents" value="@student.StudentId" />
                @student.FullName<br />
            }
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
}
    </div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Classroom/Classroom/Views/VirtualClassrooms/Details.cshtml
@model Classroom.Models.VirtualClassroom

@{
    ViewBag.Title = "Details";
}
<div>
        <h4>VirtualClassroom</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Course.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Course.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Semester.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Semester.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.AdministratorId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AdministratorId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ClassroomName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ClassroomName)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "StudentClassroom")
    </p>

Classroom/Classroom/Views/VirtualClassrooms/InstructorClassroom.cshtml
@model Classroom.ViewModels.VirtualClassroomViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_InstructorClassroom.cshtml";

}

<div class="jumbotron instructor">
    Welcome to @Model.VirtualClassroom.ClassroomName
</div>

Classroom/Classroom/Views/VirtualClassrooms/StudentClassroom.cshtml
@model Classroom.ViewModels.VirtualClassroomViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_StudentClassroom.cshtml";

}

<div class="jumbotron student">
    Welcome to @Model.VirtualClassroom.ClassroomName
</div>




            

Classroom/Classroom/Views/VirtualClassrooms/_Create.cshtml
@model Classroom.ViewModels.VirtualClassroomFormViewModel


@using (Html.BeginForm("Create", "VirtualClassrooms"))
{
    @Html.AntiForgeryToken()



    <div class="col-md-6">
        <div class="form-group">
            @Html.LabelFor(m => m.ClassroomName)
            @Html.TextBoxFor(m => m.ClassroomName, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.ClassroomName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.SemesterId)
            @Html.DropDownListFor(m => m.SemesterId, new SelectList(Model.Semesters, "Id", "Title"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.SemesterId, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.CourseId)
            @Html.DropDownListFor(m => m.CourseId, new SelectList(Model.Courses, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CourseId, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Instructors)
                <div class="form-group checkboxlist">
                    @foreach (var instructor in Model.Instructors)
                {
                        <input type="checkbox" name="selectedInstructors" value="@instructor.InstructorId" />
                        @instructor.FullName<br />
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Students)
                <div class="form-group checkboxlist">
                    @foreach (var student in Model.Students)
                {
                        <input type="checkbox" name="selectedStudents" value="@student.StudentId" />
                        @student.FullName<br />
                    }
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>

}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Classroom/Classroom/Views/VirtualClassrooms/_EditAssignment.cshtml
@model Classroom.ViewModels.VirtualClassroomViewModel

@Html.AntiForgeryToken()
@Html.HiddenFor(m => m.CompletedAssignment.Id)

<div class="form-group">
    @Html.LabelFor(m => m.CompletedAssignment.Title)
    @Html.TextBoxFor(m => m.CompletedAssignment.Title, new { @class = "form-control"})
</div>

<div class="form-group">
    @Html.LabelFor(m => m.CompletedAssignment.Description)
    @Html.TextBoxFor(m => m.CompletedAssignment.Description, new {@class = "form-control"})
</div>

<div class="form-group">
    <label>Attach File</label><br /><br />
    <div class="input-group">
        <label class="input-group-btn">
            <span class="btn btn-primary">
                Browse&hellip; <input type="file" name="file" style="display: none;" multiple>
            </span>
        </label>
        <input type="text" class="form-control" placeholder="No Files Selected" readonly>
    </div>
</div>